image: python:3.6

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

test:
  stage: test
  services:
    - docker:20.10.5-dind
  before_script:
    - curl -Lo /tmp/docker.tgz https://download.docker.com/linux/static/stable/x86_64/docker-20.10.5.tgz && tar -xf /tmp/docker.tgz -C /usr/local && rm /tmp/docker.tgz && export PATH=/usr/local/docker:$PATH
    - docker info
    # Important note about this: the Docker server is on a separate host,
    # so exposed ports are at 'docker' not 'localhost', and
    # Docker containers can't reach the local runner!
  script:
    - pip install -e .
    - curl -sLo /tmp/baseball.tar.gz https://datasets.datadrivendiscovery.org/d3m/datasets/-/archive/master/datasets-master.tar.gz?path=seed_datasets_current/185_baseball_MIN_METADATA
    - tar zxf /tmp/baseball.tar.gz --strip-components=2
    - cat examples/using_d3m_datasets.ipynb | sed "s#output_path = '[^']*'#output_path = '$(pwd)/ci_output'#" | sed "s#train_dataset = '[^']*'#train_dataset = '$(pwd)/185_baseball_MIN_METADATA/TRAIN'#" | sed "s#test_dataset = '[^']*'#test_dataset = '$(pwd)/185_baseball_MIN_METADATA/TEST'#" | sed "s#score_dataset = '[^']*'#score_dataset = '$(pwd)/185_baseball_MIN_METADATA/SCORE'#" >examples/using_d3m_datasets.ci.ipynb
    - jupyter nbconvert --to notebook --execute examples/using_d3m_datasets.ci.ipynb
